Mimic.copy(File)
Mimic.copy(SuperSeed.SystemHalt)
Mimic.copy(SuperSeed.Checks)
Mimic.copy(SuperSeed.SuperSeed.Setup)
Mimic.copy(SuperSeed.ApplicationRootNamespace)
Mimic.copy(Mix.Project)
ExUnit.start()
