#!/bin/bash

current_build_pipeline_version() {
  echo $(cat .tool-versions | awk '/build_pipeline/{print $2}')
}

type bp >/dev/null 2>&1
if [[ $? -eq 0 ]]; then
  bp run "$@"
else
  version=$(current_build_pipeline_version)
  echo -e "I'm missing the 'bp' binary provided by ASDF dependency 'build_pipeline'"
  echo -e "Look in github in the platforms repo, in the scripts folder for ./scripts/setup_macos_dev_environment,"
  echo -e "find the sections\n -install_asdf\n- configure_build_pipeline\n"
  echo -e "...and run the parts of that you need to\nTHEN run:\n"
  echo -e "asdf install build_pipeline $version"
  exit 1
fi
