#!/bin/bash

find_result=$(find test -name "*_test.ex" | grep ".")
result=$?
if [ $result -eq 0 ]; then
  echo "Tests files should be called '*_test.exs' not '*_test.ex'"
  echo "$find_result" | while read -r res; do echo " - $res"; done
  exit 1
fi
